### PR TITLE
Multi synth

### PR DESCRIPTION
**Pull request by fleeingdolphin**
this PR adapts the frontend to work with multiple synthetic 'ecosystems'
- [ ] added one usm,fum,oracle state for every ecosystem
- [ ] moved blockchain interactions (write actions) to a single file
- [ ] aded a select to choose the ecosystem to use
- [ ] removed ethers.js contract objects from state, choosing instead to build them every time
- [ ] takes advantage of redux to reuse state of already-loaded ecosystems

known issues
- [ ] oracle prices are duplicated (especially ETH) for every 'ecosystem', we could have the prices separate from the ecosystem to fix it

please only merge after #1

### CODE REVIEW

**Comment by bitsandtea** [comment]
- When Minting ETH on WBTC Synth, I get for 2 ETH -> 0.004 WBTC. However the numbers under WBTC synth table do not change:  Market Cap, Mint Price, Burn Price, Total Supply, No. of Mints, No. of Burns are not updating (tried refresh and reconnect).
- [minor] The BURN button says (USM), should it say ({ASSET})?
- WBTC funder does not update stat numbers underneath on burn and mint (neither of them):

**Init:**
```
Market Cap | Ξ 0.11 | $ 240.85
Mint Price | Ξ 0.01013 | $ 22.52
Burn Price | Ξ 0.01013 | $ 22.52
Total Supply | - | 10.69
No. of Mints | - | 15
No. of Burns | - | 10
```

**Fund 1 ETH:**
```
Market Cap | Ξ 0.11 | $ 240.84
Mint Price | Ξ 0.01013 | $ 22.52
Burn Price | Ξ 0.01013 | $ 22.52
Total Supply | - | 10.69
No. of Mints | - | 15
No. of Burns | - | 10
```

- USDC synth Init shows high numbers too:

```
Market Cap | Ξ 0.04 | $ 81.55
Mint Price | Ξ 195.64399 | $ 435,143.54
Burn Price | Ξ 176.26963 | $ 392,051.86
Total Supply | - | 0.00
No. of Mints | - | 4
No. of Burns | - | 1
```
Also not sure if its by design, but I ended up with a few separate FUM balances (different tokens / same name).

In some cases I am getting very large numbers, such as here for SPICE:

image

After refreshing:
image

Minting and burning works well in all cases, there are issues with data display though.

**Comment by juanpcapurro** [comment]
> When Minting ETH on WBTC Synth, I get for 2 ETH -> 0.004 WBTC. However the numbers under WBTC synth table do not change: Market Cap, Mint Price, Burn Price, Total Supply, No. of Mints, No. of Burns are not updating (tried refresh and reconnect).

> WBTC funder does not update stat numbers underneath on burn and mint (neither of them):

Currently there's no update triggered after an operation, so these numbers not changing is expected.

The way the amount of mint/burns is computed is kind of broken by design, because it tries to get events by listening directly in the frontend from the block the contract was deployed, and that starts to get really slow after a few thousand blocks.

> [minor] The BURN button says (USM), should it say ({ASSET})?

yes, it should. Good catch, I'll update it.

> Also not sure if its by design, but I ended up with a few separate FUM balances (different tokens / same name).

That's expected with the existing contracts, but all tokens will have different names after [the relevant pr is merged](https://github.com/spicedao/usm-synthetic/pull/8)

> In some cases I am getting very large numbers, such as here for SPICE:

Well that I have no idea why it happens, but I'll look into it and get back to you.

**Comment by juanpcapurro** [comment]
@bitsandtea sorry I can't replicate the 'high values' thing

this is an example of a funding token burn:

image

do you have anything that can help me reproduce it? perhaps a video/image like above with logs, so I can get a better insight on what causes it?

The cards get their values to display directly from redux's state, the only way to modify it is via an action, and I don't see any action dispatched after minting, only the `NETWORK_LOADED` when I connect metamask.

**Comment by bitsandtea** [comment]
Hey Juan, I am still getting the massive numbers bug. Here is a video showing it running on my localhost:
https://youtu.be/W5r_BZypAaw
Another Screenshot:
Screen Shot 2021-04-23 at 8 32 39 PM

I literally just build it, ran it locally and went on to look clicked Connect for my metamask and then switched between assets. I believe it is something like a 'default value' somewhere messing up the calculations in the view.

I also have the log file here:

```
og.js:24 [HMR] Waiting for update signal from WDS...
redux-logger.js:1  action NETWORK_LOADED @ 20:31:46.979
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
index.js:1 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `App`. See https://reactjs.org/link/warning-keys for more information.
    at option
    at App (http://localhost:3000/USM-Stats/static/js/main.chunk.js:69:3)
    at ConnectFunction (http://localhost:3000/USM-Stats/static/js/0.chunk.js:94048:75)
    at Provider (http://localhost:3000/USM-Stats/static/js/0.chunk.js:93761:20)
console.<computed> @ index.js:1
redux-logger.js:1  action ORACLE_PRICE_ETH_COINGECKO @ 20:31:47.099
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
webpackHotDevClient.js:138 src/HealthCard.js
  Line 4:10:  'Button' is defined but never used  no-unused-vars

src/redux/interactions.js
  Line 62:25:  Expected '!==' and instead saw '!='  eqeqeq
printWarnings @ webpackHotDevClient.js:138
oracles.js:28 Object
oracles.js:29 0.588806
redux-logger.js:1  action ORACLE_PRICE_SYNTH_COINGECKO @ 20:31:47.145
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action ORACLE_PRICE_COINGECKO @ 20:31:47.160
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action USM_TOTAL_SUPPLY @ 20:31:48.381
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action USM_DEBT_RATIO @ 20:31:48.400
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action USM_COLLATERAL @ 20:31:48.495
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action USM_ETH_BUFFER @ 20:31:48.515
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action USM_PRICE @ 20:31:49.077
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action ORACLE_PRICE_RAW_ETH @ 20:31:49.089
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action ORACLE_PRICE_RAW_SYNTH @ 20:31:49.097
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action ORACLE_PRICE_CACHED @ 20:31:49.146
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action ORACLE_PRICE_LATEST @ 20:31:49.157
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action FUM_PRICE @ 20:31:49.167
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action FUM_TOTAL_SUPPLY @ 20:31:49.857
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
inpage.js:1 MetaMask: 'ethereum.enable()' is deprecated and may be removed in the future. Please use the 'eth_requestAccounts' RPC method instead.
For more information, see: https://eips.ethereum.org/EIPS/eip-1102
enable @ inpage.js:1
redux-logger.js:1  action METAMASK_LOADED @ 20:32:05.428
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action ECOSYSTEM_CHANGED @ 20:32:11.394
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action NETWORK_LOADED @ 20:32:11.395
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action ORACLE_PRICE_ETH_COINGECKO @ 20:32:11.577
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
oracles.js:28 Object
oracles.js:29 0.588806
redux-logger.js:1  action ORACLE_PRICE_SYNTH_COINGECKO @ 20:32:11.683
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action ORACLE_PRICE_COINGECKO @ 20:32:11.690
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action USM_TOTAL_SUPPLY @ 20:32:12.441
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action USM_COLLATERAL @ 20:32:12.468
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action USM_DEBT_RATIO @ 20:32:12.485
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action USM_ETH_BUFFER @ 20:32:12.498
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action FUM_TOTAL_SUPPLY @ 20:32:12.511
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action ORACLE_PRICE_CACHED @ 20:32:13.028
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action ORACLE_PRICE_LATEST @ 20:32:13.036
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action FUM_PRICE @ 20:32:13.064
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action USM_PRICE @ 20:32:13.118
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action ORACLE_PRICE_RAW_ETH @ 20:32:13.129
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action ORACLE_PRICE_RAW_SYNTH @ 20:32:13.136
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action ECOSYSTEM_CHANGED @ 20:32:16.508
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action NETWORK_LOADED @ 20:32:16.528
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action ORACLE_PRICE_ETH_COINGECKO @ 20:32:16.828
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
oracles.js:28 Object
oracles.js:29 0.588806
redux-logger.js:1  action ORACLE_PRICE_SYNTH_COINGECKO @ 20:32:16.933
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action ORACLE_PRICE_COINGECKO @ 20:32:16.942
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action FUM_TOTAL_SUPPLY @ 20:32:17.499
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action USM_ETH_BUFFER @ 20:32:17.505
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action USM_TOTAL_SUPPLY @ 20:32:17.516
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action USM_DEBT_RATIO @ 20:32:17.521
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action USM_COLLATERAL @ 20:32:17.561
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action USM_PRICE @ 20:32:18.116
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action ORACLE_PRICE_RAW_ETH @ 20:32:18.174
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action ORACLE_PRICE_RAW_SYNTH @ 20:32:18.184
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action ORACLE_PRICE_CACHED @ 20:32:18.202
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action ORACLE_PRICE_LATEST @ 20:32:18.207
redux-logger.js:1  prev state Object
redux-logger.js:1  action     Object
redux-logger.js:1  next state Object
redux-logger.js:1  action FUM_PRICE @ 20:32:18.673
redux-logger.js:1  prev state ObjectSPICE: {usm: {…}, fum: {…}, oracle: {…}}fum: {buyPrice: "0.010101655459110607", sellPrice: "0.010101655459110606", supply: "5.793447189567394721"}oracle: {coingeckoETHPrice: 2329.88, coingeckoSYNTHPrice: 0.588806, coingeckoPrice: 3956.9569603570612, rawEthPrice: 1667.09683, rawSynthPrice: 1.11826, …}usm: {supply: "28.018647982282655635", debtRatio: "0.086753533279513577", collateral: "0.064082818343358004", ethBuffer: "0.058523407429562472", buyPrice: "0.00019841824335389", …}__proto__: ObjectUSDC: {usm: {…}, fum: {…}, oracle: {…}}WBTC: {usm: {…}, fum: {…}, oracle: {…}}app: {ecosystem: "USDC", provider: JsonRpcProvider, metamask: Web3Provider, metamaskSigner: JsonRpcSigner}__proto__: Object
redux-logger.js:1  action     ObjectbuyPrice: "3176.817667340619599518"sellPrice: "3176.817667340619597875"type: "FUM_PRICE"__proto__: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
redux-logger.js:1  next state ObjectSPICE: fum: {buyPrice: "0.010101655459110607", sellPrice: "0.010101655459110606", supply: "5.793447189567394721"}oracle: {coingeckoETHPrice: 2329.88, coingeckoSYNTHPrice: 0.588806, coingeckoPrice: 3956.9569603570612, rawEthPrice: 1667.09683, rawSynthPrice: 1.11826, …}usm: {supply: "28.018647982282655635", debtRatio: "0.086753533279513577", collateral: "0.064082818343358004", ethBuffer: "0.058523407429562472", buyPrice: "0.00019841824335389", …}__proto__: ObjectUSDC: fum: {supply: "0.000608950592570659", buyPrice: "3176.817667340619599518", sellPrice: "3176.817667340619597875"}oracle: {coingeckoETHPrice: 2329.88, coingeckoSYNTHPrice: 0.588806, coingeckoPrice: 3956.9569603570612, rawEthPrice: 1667.09683, rawSynthPrice: 1.11826, …}usm: {ethBuffer: "1.934525001016008963", supply: "0.000187404441632359", debtRatio: "0.016789187262961659", collateral: "1.96755871269430543", buyPrice: "176.269630487736304864", …}__proto__: ObjectWBTC: fum: {supply: "5.793447189567394721", buyPrice: "0.010101655459110607", sellPrice: "0.010101655459110606"}oracle: {coingeckoETHPrice: 2329.88, coingeckoSYNTHPrice: 0.588806, coingeckoPrice: 3956.9569603570612, cachedPrice: "5039.859153558", latestPrice: "1490.79536959204478386", …}usm: {supply: "28.018647982282655635", collateral: "0.064082818343358004", debtRatio: "0.086753533279513577", ethBuffer: "0.058523407429562472", buyPrice: "0.00019841824335389", …}__proto__: Objectapp: ecosystem: "USDC"metamask: Web3Provider {_isProvider: true, _events: Array(0), _emitted: {…}, formatter: Formatter, anyNetwork: false, …}metamaskSigner: JsonRpcSigner {_isSigner: true, provider: Web3Provider, _index: 0, _address: null}provider: JsonRpcProvider {_isProvider: true, _events: Array(0), _emitted: {…}, formatter: Formatter, anyNetwork: false, …}__proto__: Object__proto__: Object
DevTools failed to load SourceMap: Could not load content for chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sourcemaps/disable-console.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sourcemaps/contentscript.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sourcemaps/inpage.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://dmkamcknogkgcdfhhbddcghachkejeap/browser-polyfill.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```

**Comment by juanpcapurro** [comment]
well I troubleshooted it and it looks like what I feared: it's a race condition 🙃

The problem is that the requests for the usm/fum prices are started with a given ecosystem in mind (think the `getUSMPrice` in `src/redux/interactions/cdp.js`), but it isn't stored in the call stack in any way, and when the request returns and the actions to modify the state are dispatched, it is saved to the currently active ecosystem, which could be a different one.

The percieved error I believe is the data for WBTC being displayed in SCIFI

The fix would be to,
- when calling the update, have some information on what ecosystem it's for alongside it
- when dispatching the action, include that information
- in the reducer, use that information to update the relevant ecosystem.

This change should be implemented for a lot of updates, so I think it'll be best to defer it to another task.

**Comment by bitsandtea** [comment]
> well I troubleshooted it and it looks like what I feared: it's a race condition 🙃
> 
> The problem is that the requests for the usm/fum prices are started with a given ecosystem in mind (think the `getUSMPrice` in `src/redux/interactions/cdp.js`), but it isn't stored in the call stack in any way, and when the request returns and the actions to modify the state are dispatched, it is saved to the currently active ecosystem, which could be a different one.
> 
> The percieved error I believe is the data for WBTC being displayed in SCIFI
> 
> The fix would be to,
> 
> * when calling the update, have some information on what ecosystem it's for alongside it
> * when dispatching the action, include that information
> * in the reducer, use that information to update the relevant ecosystem.
> 
> This change should be implemented for a lot of updates, so I think it'll be best to defer it to another task.

I have created a separate issue for it:
https://github.com/spicedao/USM-Stats/issues/8

Merging this for now.

**Pull request merged**
